// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/child.vue')['default']
    ConditionBar: typeof import('./src/components/CurdViews/ConditionBar/ConditionBar.vue')['default']
    CurdTable: typeof import('./src/components/CurdViews/CurdTable/CurdTable.vue')['default']
    CurdViews: typeof import('./src/components/CurdViews/index.vue')['default']
    DataTable: typeof import('./src/components/CurdViews/DataTable/DataTable.vue')['default']
    EditTable: typeof import('./src/components/CurdViews/EditTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FlowBar: typeof import('./src/components/CurdViews/FlowBar/FlowBar.vue')['default']
    FormData: typeof import('./src/components/CurdViews/FormData/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Overlay: typeof import('./src/components/Overlay/index.vue')['default']
    Propover: typeof import('./src/components/Propover/index.vue')['default']
    ResultList: typeof import('./src/components/CurdViews/ResultList/index.vue')['default']
    Toasts: typeof import('./src/components/Toasts/toasts.vue')['default']
    Tree: typeof import('./src/components/CurdViews/Tree/Tree.vue')['default']
  }
}

export { }
